---
php_version: 7.1

php_enable_php_fpm: false
php_short_open_tag: true

php_enable_webserver: true
php_webserver_daemon: "apache2"

php_opcache_enabled_in_ini: false
php_opcache_enable_cli: "1"
php_apc_enabled_in_ini: false
php_enable_apc: true

php_date_timezone: "UTC"

php_extensions:
    - "php{{ php_version }}-dev"
    - "php{{ php_version }}-cli"
    - "php{{ php_version }}-apcu"
    - "php{{ php_version }}-bcmath"
    - "php{{ php_version }}-mcrypt"
    - "php{{ php_version }}-curl"
    - "php{{ php_version }}-mysql"
    - "php{{ php_version }}-pgsql"
    - "php{{ php_version }}-imagick"
    - "php{{ php_version }}-gd"
    - "php{{ php_version }}-soap"
    - "php{{ php_version }}-mbstring"
    - "php{{ php_version }}-bcmath"
    - "php{{ php_version }}-zip"
    - "php{{ php_version }}-bz2"
    - "php{{ php_version }}-sqlite3"
    - "php{{ php_version }}-simplexml"
    - "php{{ php_version }}-mongodb"

php_extra_packages: []

php_apacherelated:
    - "php{{ php_version }}"
    - "libapache2-mod-php{{ php_version }}"

php_xdebug:
    - "php{{ php_version }}-xdebug"

php_packages: "{{ php_extensions + php_apacherelated + php_xdebug + php_extra_packages}}"

php_conf_paths:
    - "/etc/php/{{ php_version }}/fpm"
    - "/etc/php/{{ php_version }}/apache2"
    - "/etc/php/{{ php_version }}/cli"

php_extension_conf_paths:
    - "/etc/php/{{ php_version }}/fpm/conf.d"
    - "/etc/php/{{ php_version }}/apache2/conf.d"
    - "/etc/php/{{ php_version }}/cli/conf.d"